### ISSUE TITLE
Firefox add-on stopped working properly

### ISSUE THREAD

**Issue by dimitriovic** [ddict/extension#3]
Hi,
I'm using Ddict on Firefox since a long time and just after Ffx updated Ddict stopped translating in my language. When trying to set up my language as it should be, the boxes are empty and I can no longer choose what language to translate to.
Now I've heard Firefox add-on is no more available for Firefox but still,the extension was working fine all this time. So any tip on how can I choose my language so I can continue to use Ddict on Firefox ?

thank you

ps. I've found another extension but Ddict is my 1st choice, I would prefer it over others if possible.

![cQLX80tbt3](https://user-images.githubusercontent.com/92334523/145814472-6cfd5468-3071-417d-acad-b1ddd518f17c.jpg)

**Comment by ddo** [comment]
hello, can you inspect the page and give me the error in the console?
btw, i'm submitting new firefox extension and it is in the queue for reviewing before publishing on firefox store(it takes long time)

**Comment by dimitriovic** [comment]
hello ddo ! thank you for your reply. happy to know you're submitting your extension for Firefox.
here is the console window's content:

![firefox_PpBRhSfszE](https://user-images.githubusercontent.com/92334523/146029278-0c0cdb97-cd73-4d89-9253-873ad6dabc77.jpg)
![firefox_v3OE1BB2yR](https://user-images.githubusercontent.com/92334523/146029404-53c29e79-ba7b-4e7e-84ea-2f996fa99a87.jpg)

**Comment by ddo** [comment]
i'm fixing it

**Comment by ddo** [comment]
The verification took time, but now it's approved on the Firefox gallary: https://addons.mozilla.org/en-US/firefox/addon/ddict/
Thanks for your report
